apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: petclinic
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: web-app
  spec:
    containers:
    - name: server
      image: sleshchenko/petclinic
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
          memory: 512Mi
      volumeMounts:
      - mountPath: /projects
        name: projects
    volumes:
    - name: projects
      persistentVolumeClaim:
        claimName: projects
- kind: Service
  apiVersion: v1
  metadata:
    name: petclinic
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: web-app
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: web-app
- apiVersion: v1
  kind: Route
  metadata:
    name: nodejs-web-endpoint
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: web-app
  spec:
    to:
      kind: Service
      name: petclinic
    port:
      targetPort: web
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: projects
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: web-app
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: Pod
  metadata:
    name: mysql-petclinic
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: mysql
  spec:
    containers:
    - name: mysql
      image: centos/mysql-57-centos7
      env:
      - name: MYSQL_USER
        value: petclinic
      - name: MYSQL_PASSWORD
        value: petclinic
      - name: MYSQL_ROOT_PASSWORD
        value: petclinic
      - name: MYSQL_DATABASE
        value: petclinic
      volumeMounts:
      - mountPath: /var/lib/mysql/data
        name: mysql-storage
      ports:
      - containerPort: 3306
        protocol: TCP
      resources:
        limits:
          memory: 512Mi
    volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-storage
- kind: Service
  apiVersion: v1
  metadata:
    name: mysql
    labels:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: mysql
  spec:
    ports:
      - name: mysql
        port: 3306
        targetPort: 3306
    selector:
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/component: mysql
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: petclinic
    name: mysql-storage
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
